export const ACHIVEMENT_ADD_REQUEST = "ACHIVEMENT_ADD_REQUEST";
export const ACHIVEMENT_ADD_SUCCESS = "ACHIVEMENT_ADD_SUCCESS";
export const ACHIVEMENT_ADD_FAIL = "ACHIVEMENT_ADD_FAIL";
export const ACHIVEMENT_ADD_RESET = "ACHIVEMENT_ADD_RESET";

export const ACHIVEMENT_LIST_REQUEST = "ACHIVEMENT_LIST_REQUEST";
export const ACHIVEMENT_LIST_SUCCESS = "ACHIVEMENT_LIST_SUCCESS";
export const ACHIVEMENT_LIST_FAIL = "ACHIVEMENT_LIST_FAIL";

export const ACHIVEMENT_DELETE_REQUEST = "ACHIVEMENT_DELETE_REQUEST";
export const ACHIVEMENT_DELETE_SUCCESS = "ACHIVEMENT_DELETE_SUCCESS";
export const ACHIVEMENT_DELETE_FAIL = "ACHIVEMENT_DELETE_FAIL";
export const ACHIVEMENT_DELETE_RESET = "ACHIVEMENT_DELETE_RESET";

export const ACHIVEMENT_UPDATE_REQUEST = "ACHIVEMENT_UPDATE_REQUEST";
export const ACHIVEMENT_UPDATE_SUCCESS = "ACHIVEMENT_UPDATE_SUCCESS";
export const ACHIVEMENT_UPDATE_FAIL = "ACHIVEMENT_UPDATE_FAIL";
export const ACHIVEMENT_UPDATE_RESET = "ACHIVEMENT_UPDATE_RESET";
