export const ADMINLOGIN_ADD_REQUEST = "ADMINLOGIN_ADD_REQUEST";
export const ADMINLOGIN_ADD_SUCCESS = "ADMINLOGIN_ADD_SUCCESS";
export const ADMINLOGIN_ADD_FAIL = "ADMINLOGIN_ADD_FAIL";
export const ADMINLOGIN_ADD_RESET = "ADMINLOGIN_ADD_RESET";

export const ADMINLOGIN_LIST_REQUEST = "ADMINLOGIN_LIST_REQUEST";
export const ADMINLOGIN_LIST_SUCCESS = "ADMINLOGIN_LIST_SUCCESS";
export const ADMINLOGIN_LIST_FAIL = "ADMINLOGIN_LIST_FAIL";

export const ADMINLOGIN_DELETE_REQUEST = "ADMINLOGIN_DELETE_REQUEST";
export const ADMINLOGIN_DELETE_SUCCESS = "ADMINLOGIN_DELETE_SUCCESS";
export const ADMINLOGIN_DELETE_FAIL = "ADMINLOGIN_DELETE_FAIL";
export const ADMINLOGIN_DELETE_RESET = "ADMINLOGIN_DELETE_RESET";

export const ADMINLOGIN_UPDATE_REQUEST = "ADMINLOGIN_UPDATE_REQUEST";
export const ADMINLOGIN_UPDATE_SUCCESS = "ADMINLOGIN_UPDATE_SUCCESS";
export const ADMINLOGIN_UPDATE_FAIL = "ADMINLOGIN_UPDATE_FAIL";
export const ADMINLOGIN_UPDATE_RESET = "ADMINLOGIN_UPDATE_RESET";
