export const AWARD_ADD_REQUEST = "AWARD_ADD_REQUEST";
export const AWARD_ADD_SUCCESS = "AWARD_ADD_SUCCESS";
export const AWARD_ADD_FAIL = "AWARD_ADD_FAIL";
export const AWARD_ADD_RESET = "AWARD_ADD_RESET";

export const AWARD_LIST_REQUEST = "AWARD_LIST_REQUEST";
export const AWARD_LIST_SUCCESS = "AWARD_LIST_SUCCESS";
export const AWARD_LIST_FAIL = "AWARD_LIST_FAIL";

export const AWARD_DELETE_REQUEST = "AWARD_DELETE_REQUEST";
export const AWARD_DELETE_SUCCESS = "AWARD_DELETE_SUCCESS";
export const AWARD_DELETE_FAIL = "AWARD_DELETE_FAIL";
export const AWARD_DELETE_RESET = "AWARD_DELETE_RESET";

export const AWARD_UPDATE_REQUEST = "AWARD_UPDATE_REQUEST";
export const AWARD_UPDATE_SUCCESS = "AWARD_UPDATE_SUCCESS";
export const AWARD_UPDATE_FAIL = "AWARD_UPDATE_FAIL";
export const AWARD_UPDATE_RESET = "AWARD_UPDATE_RESET";
