export const COMMENT_ADD_REQUEST = "COMMENT_ADD_REQUEST";
export const COMMENT_ADD_SUCCESS = "COMMENT_ADD_SUCCESS";
export const COMMENT_ADD_FAIL = "COMMENT_ADD_FAIL";
export const COMMENT_ADD_RESET = "COMMENT_ADD_RESET";

export const COMMENT_LIST_REQUEST = "COMMENT_LIST_REQUEST";
export const COMMENT_LIST_SUCCESS = "COMMENT_LIST_SUCCESS";
export const COMMENT_LIST_FAIL = "COMMENT_LIST_FAIL";

export const POSTCOMMENT_LIST_REQUEST = "POSTCOMMENT_LIST_REQUEST";
export const POSTCOMMENT_LIST_SUCCESS = "POSTCOMMENT_LIST_SUCCESS";
export const POSTCOMMENT_LIST_FAIL = "POSTCOMMENT_LIST_FAIL";

export const COMMENT_DELETE_REQUEST = "COMMENT_DELETE_REQUEST";
export const COMMENT_DELETE_SUCCESS = "COMMENT_DELETE_SUCCESS";
export const COMMENT_DELETE_FAIL = "COMMENT_DELETE_FAIL";
export const COMMENT_DELETE_RESET = "COMMENT_DELETE_RESET";

export const COMMENT_UPDATE_REQUEST = "COMMENT_UPDATE_REQUEST";
export const COMMENT_UPDATE_SUCCESS = "COMMENT_UPDATE_SUCCESS";
export const COMMENT_UPDATE_FAIL = "COMMENT_UPDATE_FAIL";
export const COMMENT_UPDATE_RESET = "COMMENT_UPDATE_RESET";

export const COMMENT_REPLY_LIST_REQUEST = "COMMENT_REPLY_LIST_REQUEST";
export const COMMENT_REPLY_LIST_SUCCESS = "COMMENT_REPLY_LIST_SUCCESS";
export const COMMENT_REPLY_LIST_FAIL = "COMMENT_REPLY_LIST_FAIL";

export const POSTCOMMENT_REPLY_REQUEST = "POSTCOMMENT_REPLY_REQUEST";
export const POSTCOMMENT_REPLY_SUCCESS = "POSTCOMMENT_REPLY_SUCCESS";
export const POSTCOMMENT_REPLY_FAIL = "POSTCOMMENT_REPLY_FAIL";

export const FEEDBACKCOMMENT_REPLY_REQUEST = "FEEDBACKCOMMENT_REPLY_REQUEST";
export const FEEDBACKCOMMENT_REPLY_SUCCESS = "FEEDBACKCOMMENT_REPLY_SUCCESS";
export const FEEDBACKCOMMENT_REPLY_FAIL = "FEEDBACKCOMMENT_REPLY_FAIL";

export const SUGGESTION_LIST_REQUEST = "SUGGESTION_LIST_REQUEST";
export const SUGGESTION_LIST_SUCCESS = "SUGGESTION_LIST_SUCCESS";
export const SUGGESTION_LIST_FAIL = "SUGGESTION_LIST_FAIL";
