export const CONTRIBUTION_ADD_REQUEST = "CONTRIBUTION_ADD_REQUEST";
export const CONTRIBUTION_ADD_SUCCESS = "CONTRIBUTION_ADD_SUCCESS";
export const CONTRIBUTION_ADD_FAIL = "CONTRIBUTION_ADD_FAIL";
export const CONTRIBUTION_ADD_RESET = "CONTRIBUTION_ADD_RESET";

export const CONTRIBUTION_LIST_REQUEST = "CONTRIBUTION_LIST_REQUEST";
export const CONTRIBUTION_LIST_SUCCESS = "CONTRIBUTION_LIST_SUCCESS";
export const CONTRIBUTION_LIST_FAIL = "CONTRIBUTION_LIST_FAIL";

export const CONTRIBUTION_DELETE_REQUEST = "CONTRIBUTION_DELETE_REQUEST";
export const CONTRIBUTION_DELETE_SUCCESS = "CONTRIBUTION_DELETE_SUCCESS";
export const CONTRIBUTION_DELETE_FAIL = "CONTRIBUTION_DELETE_FAIL";
export const CONTRIBUTION_DELETE_RESET = "CONTRIBUTION_DELETE_RESET";

export const CONTRIBUTION_UPDATE_REQUEST = "CONTRIBUTION_UPDATE_REQUEST";
export const CONTRIBUTION_UPDATE_SUCCESS = "CONTRIBUTION_UPDATE_SUCCESS";
export const CONTRIBUTION_UPDATE_FAIL = "CONTRIBUTION_UPDATE_FAIL";
export const CONTRIBUTION_UPDATE_RESET = "CONTRIBUTION_UPDATE_RESET";
