export const DASHBOARD_ADD_REQUEST = "DASHBOARD_ADD_REQUEST";
export const DASHBOARD_ADD_SUCCESS = "DASHBOARD_ADD_SUCCESS";
export const DASHBOARD_ADD_FAIL = "DASHBOARD_ADD_FAIL";
export const DASHBOARD_ADD_RESET = "DASHBOARD_ADD_RESET";

export const DASHBOARD_LIST_REQUEST = "DASHBOARD_LIST_REQUEST";
export const DASHBOARD_LIST_SUCCESS = "DASHBOARD_LIST_SUCCESS";
export const DASHBOARD_LIST_FAIL = "DASHBOARD_LIST_FAIL";

export const DASHBOARD_DELETE_REQUEST = "DASHBOARD_DELETE_REQUEST";
export const DASHBOARD_DELETE_SUCCESS = "DASHBOARD_DELETE_SUCCESS";
export const DASHBOARD_DELETE_FAIL = "DASHBOARD_DELETE_FAIL";
export const DASHBOARD_DELETE_RESET = "DASHBOARD_DELETE_RESET";

export const DASHBOARD_UPDATE_REQUEST = "DASHBOARD_UPDATE_REQUEST";
export const DASHBOARD_UPDATE_SUCCESS = "DASHBOARD_UPDATE_SUCCESS";
export const DASHBOARD_UPDATE_FAIL = "DASHBOARD_UPDATE_FAIL";
export const DASHBOARD_UPDATE_RESET = "DASHBOARD_UPDATE_RESET";
