export const GALLARY_ADD_REQUEST = "GALLARY_ADD_REQUEST";
export const GALLARY_ADD_SUCCESS = "GALLARY_ADD_SUCCESS";
export const GALLARY_ADD_FAIL = "GALLARY_ADD_FAIL";
export const GALLARY_ADD_RESET = "GALLARY_ADD_RESET";

export const GALLARY_LIST_REQUEST = "GALLARY_LIST_REQUEST";
export const GALLARY_LIST_SUCCESS = "GALLARY_LIST_SUCCESS";
export const GALLARY_LIST_FAIL = "GALLARY_LIST_FAIL";

export const GALLARY_DELETE_REQUEST = "GALLARY_DELETE_REQUEST";
export const GALLARY_DELETE_SUCCESS = "GALLARY_DELETE_SUCCESS";
export const GALLARY_DELETE_FAIL = "GALLARY_DELETE_FAIL";
export const GALLARY_DELETE_RESET = "GALLARY_DELETE_RESET";

export const GALLARY_UPDATE_REQUEST = "GALLARY_UPDATE_REQUEST";
export const GALLARY_UPDATE_SUCCESS = "GALLARY_UPDATE_SUCCESS";
export const GALLARY_UPDATE_FAIL = "GALLARY_UPDATE_FAIL";
export const GALLARY_UPDATE_RESET = "GALLARY_UPDATE_RESET";
