export const LOGIN_ADD_REQUEST = "LOGIN_ADD_REQUEST";
export const LOGIN_ADD_SUCCESS = "LOGIN_ADD_SUCCESS";
export const LOGIN_ADD_FAIL = "LOGIN_ADD_FAIL";
export const LOGIN_ADD_RESET = "LOGIN_ADD_RESET";

export const LOGIN_LIST_REQUEST = "LOGIN_LIST_REQUEST";
export const LOGIN_LIST_SUCCESS = "LOGIN_LIST_SUCCESS";
export const LOGIN_LIST_FAIL = "LOGIN_LIST_FAIL";

export const LOGIN_DELETE_REQUEST = "LOGIN_DELETE_REQUEST";
export const LOGIN_DELETE_SUCCESS = "LOGIN_DELETE_SUCCESS";
export const LOGIN_DELETE_FAIL = "LOGIN_DELETE_FAIL";
export const LOGIN_DELETE_RESET = "LOGIN_DELETE_RESET";

export const LOGIN_UPDATE_REQUEST = "LOGIN_UPDATE_REQUEST";
export const LOGIN_UPDATE_SUCCESS = "LOGIN_UPDATE_SUCCESS";
export const LOGIN_UPDATE_FAIL = "LOGIN_UPDATE_FAIL";
export const LOGIN_UPDATE_RESET = "LOGIN_UPDATE_RESET";
