export const PERSONAL_ADD_REQUEST = "PERSONAL_ADD_REQUEST";
export const PERSONAL_ADD_SUCCESS = "PERSONAL_ADD_SUCCESS";
export const PERSONAL_ADD_FAIL = "PERSONAL_ADD_FAIL";
export const PERSONAL_ADD_RESET = "PERSONAL_ADD_RESET";

export const MANIFESTO_ADD_REQUEST = "MANIFESTO_ADD_REQUEST";
export const MANIFESTO_ADD_SUCCESS = "MANIFESTO_ADD_SUCCESS";
export const MANIFESTO_ADD_FAIL = "MANIFESTO_ADD_FAIL";
export const MANIFESTO_ADD_RESET = "MANIFESTO_ADD_RESET";

export const PERSONAL_LIST_REQUEST = "PERSONAL_LIST_REQUEST";
export const PERSONAL_LIST_SUCCESS = "PERSONAL_LIST_SUCCESS";
export const PERSONAL_LIST_FAIL = "PERSONAL_LIST_FAIL";

export const PERSONAL_DELETE_REQUEST = "PERSONAL_DELETE_REQUEST";
export const PERSONAL_DELETE_SUCCESS = "PERSONAL_DELETE_SUCCESS";
export const PERSONAL_DELETE_FAIL = "PERSONAL_DELETE_FAIL";
export const PERSONAL_DELETE_RESET = "PERSONAL_DELETE_RESET";

export const PERSONAL_UPDATE_REQUEST = "PERSONAL_UPDATE_REQUEST";
export const PERSONAL_UPDATE_SUCCESS = "PERSONAL_UPDATE_SUCCESS";
export const PERSONAL_UPDATE_FAIL = "PERSONAL_UPDATE_FAIL";
export const PERSONAL_UPDATE_RESET = "PERSONAL_UPDATE_RESET";
