export const POSTIMAGE_ADD_REQUEST = "POSTIMAGE_ADD_REQUEST";
export const POSTIMAGE_ADD_SUCCESS = "POSTIMAGE_ADD_SUCCESS";
export const POSTIMAGE_ADD_FAIL = "POSTIMAGE_ADD_FAIL";
export const POSTIMAGE_ADD_RESET = "POSTIMAGE_ADD_RESET";

export const POSTIMAGE_LIST_REQUEST = "POSTIMAGE_LIST_REQUEST";
export const POSTIMAGE_LIST_SUCCESS = "POSTIMAGE_LIST_SUCCESS";
export const POSTIMAGE_LIST_FAIL = "POSTIMAGE_LIST_FAIL";

export const POSTIMAGE_DELETE_REQUEST = "POSTIMAGE_DELETE_REQUEST";
export const POSTIMAGE_DELETE_SUCCESS = "POSTIMAGE_DELETE_SUCCESS";
export const POSTIMAGE_DELETE_FAIL = "POSTIMAGE_DELETE_FAIL";
export const POSTIMAGE_DELETE_RESET = "POSTIMAGE_DELETE_RESET";

export const POSTIMAGE_UPDATE_REQUEST = "POSTIMAGE_UPDATE_REQUEST";
export const POSTIMAGE_UPDATE_SUCCESS = "POSTIMAGE_UPDATE_SUCCESS";
export const POSTIMAGE_UPDATE_FAIL = "POSTIMAGE_UPDATE_FAIL";
export const POSTIMAGE_UPDATE_RESET = "POSTIMAGE_UPDATE_RESET";
