const news = [
	{
		id: "1",
		title: "hahaha",
		name: "simatokne",
		time: "dec 2021,2019",
		image: "/images/single.jpg",
		description: "  bro Lorem ipsum dolor sit amet consectetur dolor sit amet.",
		quote: "no body nobody does it better",
		img: "/images/single.jpg",
		author: "huhu",
		date: "may 21,2019",
		authimg: "/images/raj.jpg",
	},
	{
		id: "2",
		title: "hajaldna",
		name: "hajmola",
		image: "/images/home.jpg",
		description: "bro Lorem ipsum dolor sit amet consectetur dolor sit amet.",
		quote: "hahahahaha",
		img: "/images/ho.jpeg",
		author: "huhu",
		date: "apr 08,2021",
		authimg: "/images/ashish.jpg",
	},
	{
		id: "3",
		title: "dolor sit amet",
		name: "torilaure",
		image: "/images/home.jpg",
		description: "bro Lorem ipsum dolor sit amet consectetur dolor sit amet.",
		quote: "terimaa",
		img: "/images/raj.jpg",
		author: "huhu",
		date: "mayury 10,2019",
		authimg: "/images/bbk.jpg",
	},
	{
		id: "4",
		title: "dolor sit amet ",
		name: "gedey",
		image: "/images/ho.jpeg",
		description: "bro Lorem ipsum dolor sit amet consectetur dolor sit amet.",
		quote: "hahahahaha",
		img: "/images/haason.jpg",
		author: "huhu",
		date: "may 4,2010",
		authimg: "/images/bandanana.jpeg",
	},
	{
		id: "5",
		title: "huhuh",
		name: "chaman",
		image: "/images/single.jpg",
		description: "bro Lorem ipsum dolor sit amet consectetur dolor sit amet.",
		quote: "hahahahaha",
		img: "/images/single.jpg",
		author: "huhu",
		date: "apr 21,2021",
		authimg: "/images/haason.jpg",
	},
];

export default news;
